services:
  db:
    image: postgres:16
    container_name: authforge_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authforge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authforge"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: authforge_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: authforge
    ports:
      - "8080:8080"
    command: ["/app"]

volumes:
  pgdata:
